name: google-auth

on:
  push:

jobs:
  google_api_access:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: "actions/checkout@v3"

      - name: setup node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - uses: google-github-actions/auth@v1
        id: google_auth
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER_NAME }}
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          access_token_scopes: https://www.googleapis.com/auth/drive

      - name: cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-cache-${{ hashFiles('package-lock.json') }}

      - name: install dependencies
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: npm install

      - name: build
        run: npm run build

      - name: run
        run: node .
        env:
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
